name: waveform_audio_slider
description: Dart package that provides a slider in waveform style.
version: 1.0.0
repository: https://github.com/aminnzo/waveform_audio_slider

environment:
  sdk: ^3.1.3

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.17.2


dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
  flutter_lints: ^3.0.0
